create table board
(
    id           bigint generated by default as identity,
    title        varchar(255),
    content      clob,
    author       varchar(255),
    createdDate  timestamp,
    modifiedDate timestamp,
    primary key (id)
);

create table todo
(
    id        bigint generated by default as identity,
    content   varchar(255),
    completed boolean,
    toDate    date,
    category  bigint,
    primary key (id)
);

create table category
(
    id     bigint generated by default as identity,
    name   varchar(255),
    active boolean,
    primary key (id)
);
