create table board
(
    id bigint generated by default as identity,
    title varchar(255),
    content clob,
    author varchar(255),
    createAt timestamp,
    updateAt timestamp,
    primary key (id)
);