server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./timetodo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  sql:
    init:
      encoding: UTF-8
  jpa: 
    show-sql: true
    #properties:
      #hibernate:
        #format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  devtools:
    livereload:
      enabled: true
  mustache:
    servlet:
      cache: false
      expose-session-attributes: true